In [2]:
import numpy as np

#1D array
a = np.array([1, 2, 3, 4])

#2D array
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(a)
print(b)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [5]:
print("Shape of b is", b.shape)
print("Datatype of b is", b.dtype)
print("Number of dimension in b is", b.ndim)
print("Total elements in b is", b.size)

Shape of b is (2, 4)
Datatype of b is int32
Number of dimension in b is 2
Total elements in b is 8


In [10]:
#3*3 array
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Shape of c is", c.shape)
print("Number of dimension of c is", c.ndim)
print("Size of c is", c.size)

Shape of c is (3, 3)
Number of dimension of c is 2
Size of c is 9


In [8]:
# 1D indexing
print(a[0])        # first element
print(a[-1])       # last element

# 2D indexing
print(b[0, 1])     # row 0, column 1
print(b[1])        # entire row 1

# Slicing
print(a[1:3])      # elements at index 1 and 2
print(b[:, 1])     # all of column 1

1
4
2
[5 6 7 8]
[2 3]
[2 6]


In [11]:
#print second row
print(c[1])

#print the last column
print(c[:, -1])

#slice the top-left 2 by 2 section
print(c[0:2, 0:2])

[4 5 6]
[3 6 9]
[[1 2]
 [4 5]]


In [12]:
c = np.array([10, 20, 30, 40])
print("Original:", c)
print("Add 5:", c + 5)
print("Multiply by 2:", c * 2)

# Element-wise addition
d = np.array([1, 2, 3, 4])
print("Add two arrays:", c + d)

Original: [10 20 30 40]
Add 5: [15 25 35 45]
Multiply by 2: [20 40 60 80]
Add two arrays: [11 22 33 44]


In [16]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Adding 2 to every value\n", c + 2)
print("Multiply the whole array by 3\n", c * 3)
print("Subtracting [1, 2, 3] from each row\n", c - [1, 2, 3])

Adding 2 to every value
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Multiply the whole array by 3
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Subtracting [1, 2, 3] from each row
 [[0 0 0]
 [3 3 3]
 [6 6 6]]


In [17]:
##Element-wise operation

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Exponentiation:", a ** 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Exponentiation: [1 4 9]


In [21]:
c = np.array([[1,2],
              [3,4]])
d = np.array([[5,6],
              [7,8]])
print("Add c and d\n", c + d)
print("Multiply c and d\n", c * d)
print("c divided by d\n", c/d)

Add c and d
 [[ 6  8]
 [10 12]]
Multiply c and d
 [[ 5 12]
 [21 32]]
c divided by d
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [1]:
##Aggregation

In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Standard deviation:", arr.std())
print("Min:", arr.min())
print("Max:", arr.max())

Sum: 21
Mean: 3.5
Standard deviation: 1.707825127659933
Min: 1
Max: 6


In [4]:
## Axis based computation

In [10]:
# axis=0 → column-wise, axis=1 → row-wise
print("size", arr.shape)
print("Sum along columns:", arr.sum(axis=0))
print("Sum along rows:", arr.sum(axis=1))

size (2, 3)
Sum along columns: [5 7 9]
Sum along rows: [ 6 15]


In [11]:
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("shape (rows, columns)", c.shape)
print("row wise means\n", c.mean(axis=1))
print("max in each column\n", c.max(axis=0))
print("standard deviation of the whole array", c.std())

shape (rows, columns) (3, 3)
row wise means
 [2. 5. 8.]
max in each column
 [7 8 9]
standard deviation of the whole array 2.581988897471611


In [ ]:
## Array Creation Utilites in NumPy

In [12]:
import numpy as np

a = np.zeros((2, 3))
b = np.ones((3, 2))

print("Zeros:\n", a)
print("Ones:\n", b)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
# 4 X 4 array of ones
c4 = np.ones((4,4))

# 2 X 5 array of zeros
d = np.zeros((2,5))

print("4x4\n", c4)
print("2x5\n", d)

4x4
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2x5
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
c = np.full((3, 3), 7)
print("Full of 7s:\n", c)

Full of 7s:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
# 3 X 2 filled with -1
e = np.full((3,2), -1)
print("array with -1\n", e)

array with -1
 [[-1 -1]
 [-1 -1]
 [-1 -1]]


In [18]:
d = np.eye(4)
print("Identity Matrix:\n", d)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
e = np.arange(0, 10, 2)
print("Arange:\n", e)

Arange:
 [0 2 4 6 8]


In [22]:
f = np.arange(0, 21, 2) ## a range()
print("Even numbers", f)

Even numbers [ 0  2  4  6  8 10 12 14 16 18 20]


In [24]:
f = np.linspace(0, 1, 5) #inclusive of 0 and 1
print("Linspace:\n", f)

Linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [25]:
# Random floats in [0, 1)
g = np.random.rand(2, 3)

# Random integers from 10 to 99
h = np.random.randint(10, 100, size=(3, 3))

print("Random floats:\n", g)
print("Random ints:\n", h)

Random floats:
 [[0.49363408 0.89961225 0.08940227]
 [0.51834387 0.51257451 0.36317375]]
Random ints:
 [[50 67 37]
 [35 66 51]
 [72 68 99]]


In [27]:
#random matrix of size 5by5 with 0 to 9 range
i = np.random.randint(0, 9, size = (5,5))

print("5by5 int matrix\n", i)

j = np.random.rand(1, 10)
print("1d array with floats\n", j)

5by5 int matrix
 [[0 8 6 4 8]
 [0 6 4 1 3]
 [6 2 5 4 2]
 [7 4 1 3 6]
 [5 0 0 3 2]]
1d array with floats
 [[0.64213171 0.9019087  0.07578265 0.96278832 0.21677992 0.98476452
  0.72390087 0.95351166 0.28111889 0.02184832]]
